In [10]:
# !split -d -l 500 CoCl2_geno.txt geno_part_

In [1]:
import dask.dataframe as dd
import pandas as pd
import os
import torch
import numpy as np

In [2]:
import pyarrow as pa
import pyarrow.parquet as pq

In [3]:
df = pd.read_csv("96ghpptzvf-4/SData2/split_genos/geno_part_00", sep='\t', engine="python", nrows=5)

In [4]:
N = df.shape[1]

In [5]:
dtypes = dict(zip(list(df.columns), ['float64' for _ in range(N)]))

In [6]:
df = pd.read_csv("96ghpptzvf-4/SData2/split_genos/geno_part_00", sep='\t', engine="python", dtype=dtypes)

In [7]:
file_list = []
for path, currentDirectory, files in os.walk("96ghpptzvf-4/SData2/split_genos/"):
    for file in files:
        if file.startswith("geno"):
            file_list.append(file)

In [8]:
file_list = np.sort(file_list)

In [9]:
geno_t = torch.tensor(df.iloc[:,3:].to_numpy())
geno_t = geno_t.cuda()

In [10]:
for file in file_list[1:]:
    if file != "file_part_00":
        print(file)
        df = pd.read_csv("96ghpptzvf-4/SData2/split_genos/"+file, sep='\t', header=None, index_col=0, engine="python", dtype=dtypes)
        geno_t = torch.cat([geno_t, torch.tensor(df.iloc[:,3:].to_numpy()).cuda()], 0)
        del df

geno_part_01
geno_part_02
geno_part_03
geno_part_04
geno_part_05
geno_part_06
geno_part_07
geno_part_08
geno_part_09
geno_part_10
geno_part_11
geno_part_12
geno_part_13
geno_part_14
geno_part_15

In [11]:
torch.save(geno_t, 'matsui_geno_t.pt')

In [13]:
geno_t = torch.load('matsui_geno_t.pt')

#### Are the genotypes for different env different?

In [17]:
df1 = pd.read_csv("96ghpptzvf-4/SData2/CoCl2_geno.txt", sep='\t', nrows=5, engine='python')

In [16]:
df = pd.read_csv("96ghpptzvf-4/SData2/CuSO4_geno.txt", sep='\t', nrows=5, engine='python')

In [23]:
df

,c,p,gp,BYa_1C_A10.y39_A012,BYa_1C_A10.y39_A02,BYa_1C_A10.y39_A03,BYa_1C_A10.y39_A04,BYa_1C_A10.y39_A05,BYa_1C_A10.y39_A07,BYa_1C_A10.y39_A08,...,BYx_6C_H7.y44_G04,BYx_6C_H7.y44_G05,BYx_6C_H7.y44_G06,BYx_6C_H7.y44_G07,BYx_6C_H7.y44_G08,BYx_6C_H7.y44_G09,BYx_6C_H7.y44_H011,BYx_6C_H7.y44_H02,BYx_6C_H7.y44_H04,BYx_6C_H7.y44_H08
1_30335,1,30335,30335,1,2,2,1,1,2,1,...,0,1,0,0,1,1,0,0,0,0
1_30817,1,30817,30817,1,2,2,1,1,2,1,...,0,1,0,0,1,1,0,0,0,0
1_31391,1,31391,31391,1,2,2,1,1,2,1,...,0,1,0,0,1,1,0,0,0,0
1_31635,1,31635,31635,1,2,2,1,1,2,1,...,0,1,0,0,1,1,0,0,0,0
1_31755,1,31755,31755,1,2,2,1,1,2,1,...,0,1,0,0,1,1,0,0,0,0

In [19]:
df1

,c,p,gp,BYa_1C_A10.y39_A012,BYa_1C_A10.y39_A02,BYa_1C_A10.y39_A03,BYa_1C_A10.y39_A04,BYa_1C_A10.y39_A05,BYa_1C_A10.y39_A07,BYa_1C_A10.y39_A08,...,BYx_6C_H7.y44_G03,BYx_6C_H7.y44_G04,BYx_6C_H7.y44_G05,BYx_6C_H7.y44_G06,BYx_6C_H7.y44_G07,BYx_6C_H7.y44_G09,BYx_6C_H7.y44_H011,BYx_6C_H7.y44_H02,BYx_6C_H7.y44_H04,BYx_6C_H7.y44_H08
1_30335,1,30335,30335,1,2,2,1,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1_30817,1,30817,30817,1,2,2,1,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1_31391,1,31391,31391,1,2,2,1,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1_31635,1,31635,31635,1,2,2,1,1,2,1,...,0,0,1,0,0,1,0,0,0,0
1_31755,1,31755,31755,1,2,2,1,1,2,1,...,0,0,1,0,0,1,0,0,0,0

#### seems that different env have different individuals

### Examine phenotypes

In [26]:
pheno = pd.read_csv("96ghpptzvf-4/SData6/CoCl2_pheno.txt", sep='\t', engine="python")

In [27]:
pheno

,pheno,MATa,MATalpha,geno,qnorm,MATa_mid,MATalpha_mid,midparent
0,-0.021705,y39_A012,BYa_1C_A10,BYa_1C_A10.y39_A012,-0.021147,0.074002,-0.336769,-0.131384
1,-0.184045,y39_A02,BYa_1C_A10,BYa_1C_A10.y39_A02,-0.924553,-0.286352,-0.336769,-0.311561
2,-0.133887,y39_A03,BYa_1C_A10,BYa_1C_A10.y39_A03,-0.640047,-0.896266,-0.336769,-0.616517
3,-0.021991,y39_A04,BYa_1C_A10,BYa_1C_A10.y39_A04,-0.022688,0.593958,-0.336769,0.128595
4,0.088438,y39_A05,BYa_1C_A10,BYa_1C_A10.y39_A05,0.574957,0.576434,-0.336769,0.119833
...,...,...,...,...,...,...,...,...
187172,-0.095031,y44_G09,BYx_6C_H7,BYx_6C_H7.y44_G09,-0.423639,0.132665,-0.153992,-0.010663
187173,-0.135403,y44_H011,BYx_6C_H7,BYx_6C_H7.y44_H011,-0.648964,-0.928147,-0.153992,-0.541069
187174,-0.098523,y44_H02,BYx_6C_H7,BYx_6C_H7.y44_H02,-0.442672,-0.896922,-0.153992,-0.525457
187175,-0.966134,y44_H04,BYx_6C_H7,BYx_6C_H7.y44_H04,-2.175790,-0.133272,-0.153992,-0.143632
187176,-0.120731,y44_H08,BYx_6C_H7,BYx_6C_H7.y44_H08,-0.565755,0.623577,-0.153992,0.234793

In [28]:
geno_t.shape

torch.Size([7742, 187177])

In [42]:
ids = list(df1.columns[3:])

In [34]:
pheno.geno

0         BYa_1C_A10.y39_A012
1          BYa_1C_A10.y39_A02
2          BYa_1C_A10.y39_A03
3          BYa_1C_A10.y39_A04
4          BYa_1C_A10.y39_A05
                 ...
187172      BYx_6C_H7.y44_G09
187173     BYx_6C_H7.y44_H011
187174      BYx_6C_H7.y44_H02
187175      BYx_6C_H7.y44_H04
187176      BYx_6C_H7.y44_H08
Name: geno, Length: 187177, dtype: object

In [36]:
pheno = pheno.set_index('geno')

In [45]:
pheno = pheno.loc[ids]

In [46]:
pheno

,pheno,MATa,MATalpha,qnorm,MATa_mid,MATalpha_mid,midparent
geno,,,,,,,
BYa_1C_A10.y39_A012,-0.021705,y39_A012,BYa_1C_A10,-0.021147,0.074002,-0.336769,-0.131384
BYa_1C_A10.y39_A02,-0.184045,y39_A02,BYa_1C_A10,-0.924553,-0.286352,-0.336769,-0.311561
BYa_1C_A10.y39_A03,-0.133887,y39_A03,BYa_1C_A10,-0.640047,-0.896266,-0.336769,-0.616517
BYa_1C_A10.y39_A04,-0.021991,y39_A04,BYa_1C_A10,-0.022688,0.593958,-0.336769,0.128595
BYa_1C_A10.y39_A05,0.088438,y39_A05,BYa_1C_A10,0.574957,0.576434,-0.336769,0.119833
...,...,...,...,...,...,...,...
BYx_6C_H7.y44_G09,-0.095031,y44_G09,BYx_6C_H7,-0.423639,0.132665,-0.153992,-0.010663
BYx_6C_H7.y44_H011,-0.135403,y44_H011,BYx_6C_H7,-0.648964,-0.928147,-0.153992,-0.541069
BYx_6C_H7.y44_H02,-0.098523,y44_H02,BYx_6C_H7,-0.442672,-0.896922,-0.153992,-0.525457
BYx_6C_H7.y44_H04,-0.966134,y44_H04,BYx_6C_H7,-2.175790,-0.133272,-0.153992,-0.143632
BYx_6C_H7.y44_H08,-0.120731,y44_H08,BYx_6C_H7,-0.565755,0.623577,-0.153992,0.234793